# Generated by Django 3.1.6 on 2021-03-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210310_1507'),
        ('OrderService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.customer', to_field='username'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.serviceprovider', to_field='username'),
        ),
    ]
