# Generated by Django 3.1.5 on 2021-03-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
