# Generated by Django 3.1.6 on 2021-03-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_serviceprovider_cat_id'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
