# Generated by Django 3.1.6 on 2021-03-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210309_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='cat_id',
        ),
    ]
