# Generated by Django 3.1.6 on 2021-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_serviceprovider_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(default='cust', max_length=5),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user_type',
            field=models.CharField(default='sp', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
