# Generated by Django 3.1.6 on 2021-03-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_category'),
        ('registration', '0006_auto_20210310_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category'),
        ),
    ]
